Models/ErrorViewModel.cs
namespace Comunidad_Conectada.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Persona.cs
using System.ComponentModel.DataAnnotations;

namespace Comunidad_Conectada.Models
{
    public class Persona
    {
        
        public int ID { get; set; }

        [Required(ErrorMessage = "Para poder agregar a la persona es necesario ingresar el nombre")]
        [StringLength(3, ErrorMessage = "El nombre debe tener al menos 3 caracteres")]
        public string Nombre { get; set; } = string.Empty;

        [Required(ErrorMessage = "Para poder agregar a la persona es necesario ingresar los apellidos")]
        [StringLength(3, ErrorMessage = "El apellido debe tener al menos 3 caracteres")]
        public string Apellidos { get; set; } = string.Empty;

        [Required(ErrorMessage = "Para poder agregar a la persona es necesario ingresar el teléfono")]
        [Range(10000000, 99999999, ErrorMessage = "El número debe tener exactamente 8 dígitos.")]
        public int Telefono { get; set; }

        [Required(ErrorMessage = "Para poder agregar a la persona es necesario ingresar el email")]
        [EmailAddress(ErrorMessage = "El formato del email no es correcto, por favor verifique")]
        public string Email { get; set; } = string.Empty;

        [Required(ErrorMessage = "Para poder agregar a la persona es necesario ingresar el género")]
        [RegularExpression("^[MFO]$", ErrorMessage = "El género debe ser 'M' para masculino, 'F' para femenino, o 'O' en caso de otro")]
        public char Genero { get; set; } = ' ';

        [Required(ErrorMessage = "Para poder agregar a la persona es necesario ingresar la edad")]
        [Range(1, 120, ErrorMessage = "La edad debe estar entre 0 y 120 años")]
        public int Edad { get; set; }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Comunidad_Conectada.Models;
using Microsoft.AspNetCore.Mvc;

namespace Comunidad_Conectada.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PersonasController.cs
using Microsoft.AspNetCore.Mvc;
using Comunidad_Conectada.Models;
using Comunidad_Conectada.Data;

namespace Comunidad_Conectada.Controllers
{
    //GET
    public class PersonasController : Controller
    {
        public IActionResult Index()
        {
            var personas = PersonasRepo.GetAll();
            return View(personas);
        }

        public IActionResult Create()
        {
            return View(new Persona());
        }

        //POST
        [HttpPost]
        public IActionResult Create(Persona model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            PersonasRepo.Agregar(model);

            TempData["Mensaje"] = $"Persona '{model.Nombre}' agregada correctamente.";
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Personas/Create.cshtml
@model Comunidad_Conectada.Models.Persona

﻿@{
ViewData["Title"] = "Registrar persona";
}

<h1>@ViewData["Title"]</h1>

<form asp-action="Create" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    @* nombre *@
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    @* apellidos *@
    <div class="mb-3">
        <label asp-for="Apellidos" class="form-label"></label>
        <input asp-for="Apellidos" class="form-control" />
        <span asp-validation-for="Apellidos" class="text-danger"></span>
    </div>

    @* telefono *@
    <div class="mb-3">
        <label asp-for="Telefono" class="form-label"></label>
        <input asp-for="Telefono" class="form-control" />
        <span asp-validation-for="Telefono" class="text-danger"></span>
    </div>

    @* email *@
    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    @* genero *@
    <div class="mb-3">
        <label asp-for="Genero" class="form-label"></label>
        <input asp-for="Genero" class="form-control" />
        <span asp-validation-for="Genero" class="text-danger"></span>
    </div>

    @* edad *@
    <div class="mb-3">
        <label asp-for="Edad" class="form-label"></label>
        <input asp-for="Edad" class="form-control" />
        <span asp-validation-for="Edad" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-success">Agregar</button>

    <a class="btn btn-secondary" asp-action="Index">Volver</a>
</form>

Views/Personas/Index.cshtml
@model IEnumerable<Comunidad_Conectada.Models.Persona>
﻿@{
    ViewData["Title"] = "Personas registradas";
}

<h1>@ViewData["Title"]</h1>

@if (TempData["Mensaje"] is string msg)
{
    <div class="alert alert-success" role="alert" >
        @msg
    </div>
}

<p>
    <a class="btn btn-primary" asp-controller="Personas" asp-action="Create">Nueva persona</a>
</p>

@if (!Model.Any())
{
    <p>No hay personas registradas aun</p>
}
else
{
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Telefono</th>
                <th>Emal</th>
                <th>Genero</th>
                <th>Edad</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var r in Model)
            {
                <tr>
                    <td>@r.ID</td>
                    <td>@r.Nombre</td>
                    <td>@r.Apellidos</td>
                    <td>@r.Telefono</td>
                    <td>@r.Email</td>
                    <td>@r.Genero</td>
                    <td>@r.Edad</td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Comunidad_Conectada</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Comunidad_Conectada.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Comunidad_Conectada</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Comunidad_Conectada - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>